name: theflexmen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  custom_refresh_indicator: ^3.1.0
  url_launcher: ^6.2.6
  persistent_bottom_nav_bar_v2: ^5.2.3
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  rename: ^3.0.2
  intl_phone_number_input: ^0.7.4
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  andrioid: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo_app.jpg"
  image_path_ios: "assets/icons/logo_app.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/logo_app.jpg"
  macos:
    generate: true
    image_path: "assets/icons/logo_app.jpg"
  windows:
    generate: true
    image_path: "assets/icons/logo_app.jpg"
    icon_size: 48

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image_dark: assets\icons\logo_white.png
  image: assets\icons\logo.png
  fullscreen: true

